[package]
name = "ucms-rust"
version = "0.1.0"
authors = ["Martin Ashby <martin@ashbysoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
